import Header from "components/Header";
import { TKey } from "interfaces";
import { useTranslation } from "next-i18next";
import Head from "next/head";
import { useRouter } from "next/router";
import Sidebar from "./Sidebar";

const Layout: React.FC<{
  children: React.ReactElement;
}> = ({ children }): React.ReactElement => {
  const { t } = useTranslation();
  const { pathname } = useRouter();

  const tit =
    pathname === "/"
      ? t("dashboard")
      : t("dashboard") + " | " + t(pathname?.split("/")[1] as TKey);
  return (
    <>
      <Head>
        <title>{tit}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Sidebar />

      <main className="main flex flex-col md:ms-72 md:flex-grow  transition-all duration-150 ease-in">
        <div className="p-4">{children}</div>
      </main>
    </>
  );
};

export default Layout;
